CREATE TABLE IF NOT EXISTS HOTEL (
    HotelID CHAR(6),
    Street VARCHAR(20),
    Country VARCHAR(25),
    State VARCHAR(20),
    Zip CHAR(5),
    CONSTRAINT HOTELPK PRIMARY KEY (HotelID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ROOM (
    RoomHotelID CHAR(6),
    RoomNo CHAR(10),
    RType VARCHAR(10),
    RPrice FLOAT(5 , 2 ),
    RDescription VARCHAR(300),
    Floor VARCHAR(2),
    Capacity VARCHAR(2),
    CONSTRAINT ROOMPK PRIMARY KEY (RoomNo),
    CONSTRAINT ROOMFK FOREIGN KEY (RoomHotelID)
        REFERENCES HOTEL (HotelID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS BREAKFAST (
    BreakHotelID CHAR(6),
    BType VARCHAR(15),
    BPrice FLOAT(5 , 2 ),
    BDescription VARCHAR(300),
    CONSTRAINT BREAKPK PRIMARY KEY (BType),
    CONSTRAINT BREAKFK FOREIGN KEY (BreakHotelID)
        REFERENCES HOTEL (HotelID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS SERVICE (
    ServHotelID CHAR(6),
    SType VARCHAR(50),
    SPrice FLOAT(5 , 2 ),
    CONSTRAINT SERVPK PRIMARY KEY (SType),
    CONSTRAINT SERVFK FOREIGN KEY (ServHotelID)
        REFERENCES HOTEL (HotelID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CREDIT_CARD (
    CNumber CHAR(16),
    CType VARCHAR(10),
    CardAddress VARCHAR(180),
    CCode CHAR(3),
    ExpDate CHAR(7),
    CardName VARCHAR(30),
    CONSTRAINT CREDCARDPK PRIMARY KEY (CNumber)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CID VARCHAR(8),
    CustName VARCHAR(30),
    CustAddress VARCHAR(180),
    PhoneNum CHAR(10),
    Email VARCHAR(60),
    CONSTRAINT CUSTPK PRIMARY KEY (CID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS RESERVATION (
    InvoiceNo VARCHAR(10),
    ResCID VARCHAR(8),
    ResCNumber CHAR(16),
    ResDateMade DATE,
    CONSTRAINT RESPK PRIMARY KEY (InvoiceNo),
    CONSTRAINT RESFK1 FOREIGN KEY (ResCID)
        REFERENCES CUSTOMER (CID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT RESFK2 FOREIGN KEY (ResCNumber)
        REFERENCES CREDIT_CARD (CNumber)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ROOM_RESERVATION (
    InvoiceNo VARCHAR(10),
    ResHotelID CHAR(6),
    ResRoomNo CHAR(10),
    CheckInDate VARCHAR(21),
    CheckOutDate VARCHAR(21),
    CONSTRAINT RRESPK PRIMARY KEY (CheckInDate),
    CONSTRAINT RRESFK1 FOREIGN KEY (ResHotelID)
        REFERENCES ROOM (RoomHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT RRESFK2 FOREIGN KEY (ResRoomNo)
        REFERENCES ROOM (RoomNo)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS RRESV_BREAKFAST (
    ResBType VARCHAR(25),
    ResBHotelID CHAR(6),
    ResBRoomNo CHAR(10),
    ResBCheckInDate VARCHAR(21),
    NoOfOrders INT,
    CONSTRAINT BRESFK1 FOREIGN KEY (ResBType)
        REFERENCES BREAKFAST (BType)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BRESFK2 FOREIGN KEY (ResBHotelID)
        REFERENCES BREAKFAST (BreakHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BRESFK3 FOREIGN KEY (ResBHotelID)
        REFERENCES ROOM_RESERVATION (ResHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BRESFK4 FOREIGN KEY (ResBRoomNo)
        REFERENCES ROOM_RESERVATION (ResRoomNo)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BRESFK5 FOREIGN KEY (ResBCheckInDate)
        REFERENCES ROOM_RESERVATION (CheckInDate)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS RRESV_SERVICE (
    ResSType VARCHAR(50),
    ResSHotelID VARCHAR(6),
    ResSRoomNo CHAR(10),
    ResSCheckInDate VARCHAR(21),
    CONSTRAINT SRESFK1 FOREIGN KEY (ResSType)
        REFERENCES SERVICE (SType)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SRESFK2 FOREIGN KEY (ResSHotelID)
        REFERENCES SERVICE (ServHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SRESFK3 FOREIGN KEY (ResSHotelID)
        REFERENCES ROOM_RESERVATION (ResHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SRESFK4 FOREIGN KEY (ResSRoomNo)
        REFERENCES ROOM_RESERVATION (ResRoomNo)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SRESFK5 FOREIGN KEY (ResSCheckInDate)
        REFERENCES ROOM_RESERVATION (CheckInDate)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ROOM_REVIEW (
    RRevRID VARCHAR(10),
    RRevRating INT,
    RRevText VARCHAR(300),
    RRevCID VARCHAR(8),
    RRevHotelID VARCHAR(6),
    RRevRoomNo CHAR(10),
    CONSTRAINT RREVFK1 FOREIGN KEY (RRevHotelID)
        REFERENCES ROOM (RoomHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT RREVFK2 FOREIGN KEY (RRevRoomNo)
        REFERENCES ROOM (RoomNo)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT RREVFK3 FOREIGN KEY (RRevCID)
        REFERENCES CUSTOMER (CID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS BREAKFAST_REVIEW (
    BRevRID VARCHAR(10),
    BRevRating INT,
    BRevText VARCHAR(300),
    BRevCID VARCHAR(8),
    BRevHotelID VARCHAR(6),
    BRevType VARCHAR(25),
    CONSTRAINT BREVFK1 FOREIGN KEY (BRevHotelID)
        REFERENCES BREAKFAST (BreakHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BREVFK2 FOREIGN KEY (BRevType)
        REFERENCES BREAKFAST (BType)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT BREVFK3 FOREIGN KEY (BRevCID)
        REFERENCES CUSTOMER (CID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS SERVICE_REVIEW (
    SRevRID VARCHAR(10),
    SRevRating INT,
    SRevText VARCHAR(300),
    SRevCID VARCHAR(8),
    SRevHotelID VARCHAR(6),
    SRevType VARCHAR(50),
    CONSTRAINT SREVFK1 FOREIGN KEY (SRevHotelID)
        REFERENCES SERVICE (ServHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SREVFK2 FOREIGN KEY (SRevType)
        REFERENCES SERVICE (SType)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SREVFK3 FOREIGN KEY (SRevCID)
        REFERENCES CUSTOMER (CID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS DISCOUNTED_ROOM (
    DiscRoomHotelID CHAR(6),
    DiscRoomNo CHAR(10),
    Discount VARCHAR(10),
    StartDate DATE,
    EndDate DATE,
    CONSTRAINT DISCROOMFK1 FOREIGN KEY (DiscRoomHotelID)
        REFERENCES ROOM (RoomHotelID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT DISCROOMFK2 FOREIGN KEY (DiscRoomNo)
        REFERENCES ROOM (RoomNo)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;
